### ISSUE TITLE
大神，我不知道在哪里给你留言，但是我看你在微额借款用户人品预测大赛中留言了。

### ISSUE THREAD

**Issue by PGaga** [Tongzhenguo/tensorflow_app#1]
我现在在看微额借款用户人品预测大赛冠军分享的代码，运行rank.py 缺少features_type.csv ，既然您留过言 肯定也运行过，能不能发一份文件。万份感激。找了好久了，求大佬帮忙。

**Comment by Tongzhenguo** [comment]
n年前的事了，早不记得了。不过自己存一份也不难吧？
